/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPortalVerifyRouteImport } from './routes/_authenticated/portal.verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalVerifyRoute =
  AuthenticatedPortalVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/portal/verify': typeof AuthenticatedPortalVerifyRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/portal/verify': typeof AuthenticatedPortalVerifyRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/portal/verify': typeof AuthenticatedPortalVerifyRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/auth'
    | '/contact'
    | '/courses'
    | '/portal'
    | '/portal/verify'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/auth'
    | '/contact'
    | '/courses'
    | '/portal/verify'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admissions'
    | '/auth'
    | '/contact'
    | '/courses'
    | '/_authenticated/portal'
    | '/_authenticated/portal/verify'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/verify': {
      id: '/_authenticated/portal/verify'
      path: '/verify'
      fullPath: '/portal/verify'
      preLoaderRoute: typeof AuthenticatedPortalVerifyRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
  }
}

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalVerifyRoute: typeof AuthenticatedPortalVerifyRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalVerifyRoute: AuthenticatedPortalVerifyRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
